/**
 * Generate HTML audit report and summary.json.
 */

import type { AuditResult, AuditItem, PriorityAction } from '../analyzer/geo-auditor.js';
import { calculatePriorityActions } from '../analyzer/geo-auditor.js';
import type { SiteCrawlResult } from '../crawler/page-data.js';

interface ReportStrings {
  title: string;
  downloadPdf: string;
  exportCsv: string;
  exportHint: string;
  generated: string;
  pagesCrawled: string;
  time: string;
  overallScore: string;
  criticalChecks: string;
  highPriority: string;
  pagesCrawledLabel: string;
  auditResults: string;
  critical: string;
  criticalBadge: string;
  high: string;
  highBadge: string;
  medium: string;
  mediumBadge: string;
  low: string;
  lowBadge: string;
  seo: string;
  seoBadge: string;
  seoChecks: string;
  eeat: string;
  eeatBadge: string;
  eeatChecks: string;
  aeo: string;
  aeoBadge: string;
  aeoChecks: string;
  actionItemsTitle: string;
  actionItemsIntro: string;
  actionCurrentScore: string;
  actionPriority: string;
  generatedFiles: string;
  generatedFilesDesc: string;
  generatedLabel: string;
  deployTitle: string;
  deploySteps: string[];
  footer: string;
  affectedPagesLabel: string;
  showAffectedPages: string;
  hideAffectedPages: string;
}

const STRINGS_EN: ReportStrings = {
  title: 'GEO Audit Report',
  downloadPdf: 'Download PDF',
  exportCsv: 'Export CSV',
  exportHint: 'Use browser "Save as PDF" in the print dialog',
  generated: 'Generated',
  pagesCrawled: 'Pages crawled',
  time: 'Time',
  overallScore: 'Overall Score',
  criticalChecks: 'Critical Checks',
  highPriority: 'High Priority',
  pagesCrawledLabel: 'Pages Crawled',
  auditResults: 'Audit Results',
  critical: 'Critical',
  criticalBadge: 'critical',
  high: 'High Priority',
  highBadge: 'high',
  medium: 'Medium Priority',
  mediumBadge: 'medium',
  low: 'Low Priority',
  lowBadge: 'low',
  seo: 'SEO',
  seoBadge: 'seo',
  seoChecks: 'SEO Checks',
  eeat: 'E-E-A-T',
  eeatBadge: 'e-e-a-t',
  eeatChecks: 'E-E-A-T Checks',
  aeo: 'AEO',
  aeoBadge: 'aeo',
  aeoChecks: 'AEO Checks',
  actionItemsTitle: 'Your Action Items',
  actionItemsIntro: 'The items below <strong>cannot be auto-generated</strong> &mdash; they require content changes, configuration updates, or development work on your website. We&rsquo;ve sorted them by impact so you can prioritize what matters most.',
  actionCurrentScore: 'Current score',
  actionPriority: 'Priority',
  generatedFiles: 'Generated Files',
  generatedFilesDesc: 'The following GEO compliance files have been generated and are ready for deployment.',
  generatedLabel: 'Generated',
  deployTitle: 'Deployment Instructions',
  deploySteps: [
    'Copy all generated files to your web server\'s root directory',
    'Ensure <code>.well-known/</code> directory is served correctly (not blocked by server config)',
    'Add JSON-LD from <code>structured-data/</code> to your page templates\' <code>&lt;head&gt;</code> sections',
    'Update <code>security.txt</code> contact email and add your PGP key if available',
    'Review <code>robots.txt</code> AI crawler directives — adjust Allow/Disallow per your policy',
    'Validate sitemap.xml at <a href="https://www.xml-sitemaps.com/validate-xml-sitemap.html">xml-sitemaps.com</a>',
    'Test structured data at <a href="https://search.google.com/test/rich-results">Google Rich Results Test</a>',
  ],
  footer: 'Generated by <strong>geo-scraper</strong> | Generative Engine Optimization Compliance Tool',
  affectedPagesLabel: 'Affected pages',
  showAffectedPages: 'Show affected pages',
  hideAffectedPages: 'Hide affected pages',
};

const STRINGS_LT: ReportStrings = {
  title: 'GEO audito ataskaita',
  downloadPdf: 'Atsisiųsti PDF',
  exportCsv: 'Eksportuoti CSV',
  exportHint: 'Naudokite naršyklės „Išsaugoti kaip PDF" spausdinimo dialoge',
  generated: 'Sukurta',
  pagesCrawled: 'Nuskaityta puslapių',
  time: 'Laikas',
  overallScore: 'Bendras balas',
  criticalChecks: 'Kritiniai patikrinimai',
  highPriority: 'Aukštas prioritetas',
  pagesCrawledLabel: 'Nuskaityta puslapių',
  auditResults: 'Audito rezultatai',
  critical: 'Kritinis',
  criticalBadge: 'kritinis',
  high: 'Aukštas prioritetas',
  highBadge: 'aukštas',
  medium: 'Vidutinis prioritetas',
  mediumBadge: 'vidutinis',
  low: 'Žemas prioritetas',
  lowBadge: 'žemas',
  seo: 'SEO',
  seoBadge: 'seo',
  seoChecks: 'SEO patikrinimai',
  eeat: 'E-E-A-T',
  eeatBadge: 'e-e-a-t',
  eeatChecks: 'E-E-A-T patikrinimai',
  aeo: 'AEO',
  aeoBadge: 'aeo',
  aeoChecks: 'AEO patikrinimai',
  actionItemsTitle: 'Jūsų veiksmai',
  actionItemsIntro: 'Šie punktai <strong>negali būti sugeneruoti automatiškai</strong> &mdash; jiems reikia turinio pakeitimų, konfigūracijos atnaujinimų arba programavimo darbų jūsų svetainėje. Surikiavome pagal svarbą, kad galėtumėte nustatyti prioritetus.',
  actionCurrentScore: 'Dabartinis balas',
  actionPriority: 'Prioritetas',
  generatedFiles: 'Sugeneruoti failai',
  generatedFilesDesc: 'Šie GEO atitikties failai buvo sugeneruoti ir yra paruošti diegimui.',
  generatedLabel: 'Sugeneruota',
  deployTitle: 'Diegimo instrukcijos',
  deploySteps: [
    'Nukopijuokite visus sugeneruotus failus į savo žiniatinklio serverio šakninį katalogą',
    'Įsitikinkite, kad <code>.well-known/</code> katalogas aptarnaujamas teisingai (neblokuojamas serverio konfigūracijos)',
    'Pridėkite JSON-LD iš <code>structured-data/</code> į savo puslapių šablonų <code>&lt;head&gt;</code> sekcijas',
    'Atnaujinkite <code>security.txt</code> kontaktinį el. paštą ir pridėkite savo PGP raktą, jei turite',
    'Peržiūrėkite <code>robots.txt</code> DI robotų direktyvas — koreguokite Allow/Disallow pagal savo politiką',
    'Patvirtinkite sitemap.xml adresu <a href="https://www.xml-sitemaps.com/validate-xml-sitemap.html">xml-sitemaps.com</a>',
    'Patikrinkite struktūrinius duomenis <a href="https://search.google.com/test/rich-results">Google Rich Results Test</a>',
  ],
  footer: 'Sugeneravo <strong>geo-scraper</strong> | Generatyvinio variklio optimizavimo atitikties įrankis',
  affectedPagesLabel: 'Paveikti puslapiai',
  showAffectedPages: 'Rodyti paveiktus puslapius',
  hideAffectedPages: 'Slėpti paveiktus puslapius',
};

/** Map of audit item names → Lithuanian translations */
const ITEM_NAMES_LT: Record<string, string> = {
  'robots.txt': 'robots.txt',
  'sitemap.xml': 'sitemap.xml',
  'llms.txt': 'llms.txt',
  'llms-full.txt': 'llms-full.txt',
  'Structured Data (JSON-LD)': 'Struktūriniai duomenys (JSON-LD)',
  'Server-side Rendering': 'Serverio pusės atvaizdavimas',
  'AI Bot Blocking': 'DI robotų blokavimas',
  'AI Policy (ai.txt / ai.json)': 'DI politika (ai.txt / ai.json)',
  'Meta Descriptions': 'Meta aprašymai',
  'Heading Hierarchy': 'Antraščių hierarchija',
  'Content Freshness': 'Turinio naujumas',
  'Content Structure & Depth': 'Turinio struktūra ir gilumas',
  'security.txt': 'security.txt',
  'tdmrep.json': 'tdmrep.json',
  'Open Graph Tags': 'Open Graph žymės',
  'AI Content Directives': 'DI turinio direktyvos',
  'manifest.json': 'manifest.json',
  'humans.txt': 'humans.txt',
  'FAQ Content': 'DUK turinys',
  'Search Engine Indexing': 'Paieškos variklių indeksavimas',
  'Title Tags': 'Pavadinimo žymės',
  'Image Alt Text': 'Paveikslėlių alt tekstas',
  'Internal Linking': 'Vidinis susiejimas',
  'Mobile Viewport': 'Mobilusis rodymo laukas',
  'HTTPS Enforcement': 'HTTPS užtikrinimas',
  'Broken Pages': 'Neveikiantys puslapiai',
  // E-E-A-T
  'Author & Expertise Signals': 'Autoriaus ir kompetencijos signalai',
  'Trust Signals': 'Pasitikėjimo signalai',
  'Social Proof & Authority': 'Socialiniai įrodymai ir autoritetas',
  'Citation Quality': 'Citavimo kokybė',
  // AEO
  'Featured Snippet Readiness': 'Pasirengimas išskirtiniams fragmentams',
  'Voice Search Optimization': 'Balso paieškos optimizavimas',
  'Answer Format Diversity': 'Atsakymų formatų įvairovė',
  'Schema Markup Diversity': 'Schemos žymėjimo įvairovė',
};

/** Map of audit item recommendations → Lithuanian translations */
const ITEM_RECS_LT: Record<string, string> = {
  // robots.txt
  'Add /robots.txt with explicit AI crawler directives (GPTBot, ClaudeBot, PerplexityBot, etc.)':
    'Pridėkite /robots.txt su aiškiomis DI robotų direktyvomis (GPTBot, ClaudeBot, PerplexityBot ir kt.)',
  'robots.txt has comprehensive AI crawler coverage':
    'robots.txt turi išsamų DI robotų padengimą',
  'robots.txt exists but has no AI crawler directives':
    'robots.txt egzistuoja, bet neturi DI robotų direktyvų',
  // sitemap
  'Add /sitemap.xml with all discoverable URLs':
    'Pridėkite /sitemap.xml su visais aptinkamais URL adresais',
  'Sitemap is well-configured':
    'Sitemap tinkamai sukonfigūruotas',
  'Add <lastmod> dates to sitemap entries for freshness signals':
    'Pridėkite <lastmod> datas sitemap įrašams kaip naujumo signalus',
  // llms.txt
  'Add /llms.txt following the llmstxt.org spec: H1 site name, blockquote summary, H2 sections with link lists':
    'Pridėkite /llms.txt pagal llmstxt.org specifikaciją: H1 svetainės pavadinimas, citatos santrauka, H2 skyriai su nuorodų sąrašais',
  // llms-full.txt
  'Add /llms-full.txt with complete site content in markdown for bulk LLM ingestion':
    'Pridėkite /llms-full.txt su visu svetainės turiniu markdown formatu LLM įkėlimui',
  // Structured Data
  'Add JSON-LD Schema.org markup: Organization on homepage, Article on blog posts, FAQPage on FAQ sections, Product on product pages':
    'Pridėkite JSON-LD Schema.org žymėjimą: Organization pagrindiniame puslapyje, Article tinklaraščio įrašuose, FAQPage DUK skiltyse, Product produktų puslapiuose',
  'Add Organization schema to homepage for entity disambiguation':
    'Pridėkite Organization schemą pagrindiniame puslapyje subjekto atpažinimui',
  'Good structured data coverage':
    'Geras struktūrinių duomenų padengimas',
  // SSR
  'AI crawlers cannot execute JavaScript — ensure content is in initial HTML response via SSR/SSG':
    'DI robotai negali vykdyti JavaScript — užtikrinkite, kad turinys būtų pradiniame HTML atsakyme per SSR/SSG',
  'Content renders without JavaScript — good!':
    'Turinys atvaizduojamas be JavaScript — puiku!',
  // AI Bot Blocking
  'robots.txt does not block AI crawlers — good!':
    'robots.txt neblokuoja DI robotų — puiku!',
  'No AI crawlers are blocked in robots.txt':
    'Jokie DI robotai nėra blokuojami robots.txt',
  // AI Policy
  'Add /ai.txt and /ai.json to define AI interaction permissions, restrictions, and attribution requirements':
    'Pridėkite /ai.txt ir /ai.json, kad apibrėžtumėte DI sąveikos leidimus, apribojimus ir priskyrimo reikalavimus',
  'Both AI policy files are present':
    'Abu DI politikos failai yra',
  // Meta Descriptions
  'Add meaningful meta descriptions to all pages — AI engines use these for summaries and citations':
    'Pridėkite prasmingus meta aprašymus visiems puslapiams — DI varikliai juos naudoja santraukoms ir citavimui',
  'Good meta description coverage':
    'Geras meta aprašymų padengimas',
  // Heading Hierarchy
  'Fix heading hierarchy: single H1, no skipped levels (H1>H2>H3). LLMs use headings to understand content structure.':
    'Pataisykite antraščių hierarchiją: viena H1, nepraleisti lygiai (H1>H2>H3). LLM naudoja antraštes turinio struktūrai suprasti.',
  'Heading hierarchy is clean':
    'Antraščių hierarchija tvarkinga',
  // Content Freshness
  'Add dateModified to JSON-LD and keep content updated — AI-cited content is 25.7% fresher than traditional results':
    'Pridėkite dateModified į JSON-LD ir atnaujinkite turinį — DI cituojamas turinys yra 25,7% šviežesnis nei tradiciniai rezultatai',
  'Content freshness signals are strong':
    'Turinio naujumo signalai stiprūs',
  // Content Depth
  'Add more substantive content (>500 words) with clear heading structure (>=3 headings). AI engines chunk content by paragraphs under headings.':
    'Pridėkite daugiau turinio (>500 žodžių) su aiškia antraščių struktūra (>=3 antraštės). DI varikliai skaido turinį pagal pastraipas po antraštėmis.',
  'Content depth and structure are solid':
    'Turinio gilumas ir struktūra yra tvirti',
  // security.txt
  'Add /.well-known/security.txt per RFC 9116 with security contact info':
    'Pridėkite /.well-known/security.txt pagal RFC 9116 su saugumo kontaktine informacija',
  'RFC 9116 security.txt is present':
    'RFC 9116 security.txt yra',
  // tdmrep.json
  'Add /.well-known/tdmrep.json to define text/data mining rights':
    'Pridėkite /.well-known/tdmrep.json teksto/duomenų gavybos teisėms apibrėžti',
  'W3C TDM reservation is present':
    'W3C TDM rezervacija yra',
  // OG Tags
  'Add og:title and og:description to all pages for rich previews in AI responses':
    'Pridėkite og:title ir og:description visiems puslapiams turtingiems peržiūroms DI atsakymuose',
  'Good Open Graph coverage':
    'Geras Open Graph padengimas',
  // AI Content Directives
  'Add <meta name="robots" content="max-snippet:-1, max-image-preview:large"> to allow AI engines to use full content in responses':
    'Pridėkite <meta name="robots" content="max-snippet:-1, max-image-preview:large">, kad DI varikliai galėtų naudoti visą turinį atsakymuose',
  'AI content directives are well-configured':
    'DI turinio direktyvos tinkamai sukonfigūruotos',
  // manifest.json
  'Add manifest.json for site identity metadata':
    'Pridėkite manifest.json svetainės tapatybės metaduomenims',
  'Web manifest is present':
    'Žiniatinklio manifestas yra',
  // humans.txt
  'Add /humans.txt for team and technology info':
    'Pridėkite /humans.txt komandos ir technologijų informacijai',
  'humans.txt is present':
    'humans.txt yra',
  // FAQ
  'Add FAQ sections to high-traffic pages. FAQPage schema has the highest AI citation probability.':
    'Pridėkite DUK skyrius didelio lankomumo puslapiuose. FAQPage schema turi didžiausią DI citavimo tikimybę.',
  'Add FAQPage JSON-LD schema markup alongside FAQ content for maximum AI citation rates':
    'Pridėkite FAQPage JSON-LD schemos žymėjimą kartu su DUK turiniu maksimaliam DI citavimo rodikliui',
  // Search Engine Indexing
  'All search engine indexing signals are present — your site is well-configured for discovery':
    'Visi paieškos variklių indeksavimo signalai yra — jūsų svetainė tinkamai sukonfigūruota aptikimui',
  'Your site is likely not indexed by search engines. Set up Google Search Console and Bing Webmaster Tools, add a Sitemap directive to robots.txt, and remove any noindex tags':
    'Jūsų svetainė greičiausiai neindeksuota paieškos variklių. Nustatykite Google Search Console ir Bing Webmaster Tools, pridėkite Sitemap direktyvą į robots.txt ir pašalinkite noindex žymes',
  'Your site is likely not indexed by search engines. Set up Google Search Console and Bing Webmaster Tools, add a Sitemap directive to robots.txt, set canonical URLs, and remove any noindex tags':
    'Jūsų svetainė greičiausiai neindeksuota paieškos variklių. Nustatykite Google Search Console ir Bing Webmaster Tools, pridėkite Sitemap direktyvą į robots.txt, nustatykite canonical URL ir pašalinkite noindex žymes',
  // Title Tags
  'Ensure every page has a unique title tag between 30-70 characters. Include primary keyword near the beginning.':
    'Įsitikinkite, kad kiekvienas puslapis turi unikalią pavadinimo žymą tarp 30-70 simbolių. Įtraukite pagrindinį raktažodį pradžioje.',
  'Title tags are well-optimized':
    'Pavadinimo žymės gerai optimizuotos',
  // Image Alt Text
  'Add descriptive alt text to all images. Alt text helps search engines and AI models understand image content.':
    'Pridėkite aprašomąjį alt tekstą visiems paveikslėliams. Alt tekstas padeda paieškos varikliams ir DI modeliams suprasti paveikslėlių turinį.',
  'Good image alt text coverage':
    'Geras paveikslėlių alt teksto padengimas',
  'No images to check — not applicable':
    'Nėra paveikslėlių patikrinimui — netaikoma',
  // Internal Linking
  'Improve internal linking: add contextual links between related pages and ensure no pages are orphaned (unreachable from other pages).':
    'Pagerinkite vidinį susiejimą: pridėkite kontekstinius ryšius tarp susijusių puslapių ir užtikrinkite, kad nėra „našlaičių" puslapių (nepasiekiamų iš kitų puslapių).',
  'Internal linking structure is healthy':
    'Vidinio susiejimo struktūra sveika',
  // Mobile Viewport
  'Add <meta name="viewport" content="width=device-width, initial-scale=1"> to all pages for mobile-friendly rendering.':
    'Pridėkite <meta name="viewport" content="width=device-width, initial-scale=1"> į visus puslapius mobiliajam atvaizdavimui.',
  'Mobile viewport is properly configured':
    'Mobilusis rodymo laukas tinkamai sukonfigūruotas',
  // HTTPS
  'Migrate all pages to HTTPS. Search engines penalize non-HTTPS sites and browsers show security warnings.':
    'Perkelkite visus puslapius į HTTPS. Paieškos varikliai baudžia ne-HTTPS svetaines, o naršyklės rodo saugumo įspėjimus.',
  'All pages are served securely over HTTPS':
    'Visi puslapiai saugiai aptarnaujami per HTTPS',
  // Broken Pages
  'Fix or remove broken pages (4xx/5xx status codes). Broken pages waste crawl budget and harm user experience.':
    'Pataisykite arba pašalinkite neveikiančius puslapius (4xx/5xx būsenos kodai). Neveikiantys puslapiai švaisto nuskaitymo biudžetą ir kenkia naudotojo patirčiai.',
  'No broken pages detected':
    'Neveikiančių puslapių nerasta',
  // E-E-A-T
  'Add author names and bios to content pages. AI engines use author signals for E-E-A-T (Experience, Expertise, Authoritativeness, Trust) scoring.':
    'Pridėkite autorių vardus ir biografijas turinio puslapiuose. DI varikliai naudoja autoriaus signalus E-E-A-T (Patirtis, Kompetencija, Autoritetingumas, Pasitikėjimas) vertinimui.',
  'Author expertise signals are present':
    'Autoriaus kompetencijos signalai yra',
  'Add trust signals: contact information, about page, privacy policy. These are critical for E-E-A-T trust assessment by AI engines.':
    'Pridėkite pasitikėjimo signalus: kontaktinę informaciją, puslapį „Apie mus", privatumo politiką. Tai svarbu DI variklių E-E-A-T pasitikėjimo vertinimui.',
  'Trust signals are well-established':
    'Pasitikėjimo signalai gerai įtvirtinti',
  'Add social media profile links to your site. Multiple platform presence signals authority and helps AI engines verify entity identity.':
    'Pridėkite socialinių tinklų profilių nuorodas į savo svetainę. Buvimas keliose platformose signalizuoja autoritetą ir padeda DI varikliams patvirtinti subjekto tapatybę.',
  'Social proof signals are strong':
    'Socialinių įrodymų signalai stiprūs',
  'Add data-backed claims (statistics, research citations, expert quotes) to content pages. AI engines favor well-cited content for featured responses.':
    'Pridėkite duomenimis pagrįstus teiginius (statistiką, tyrimų citatas, ekspertų citatas) turinio puslapiuose. DI varikliai teikia pirmenybę gerai cituojamam turiniui.',
  'Content is well-cited with data and sources':
    'Turinys gerai cituojamas su duomenimis ir šaltiniais',
  // AEO
  'Add concise answer paragraphs (40-60 words) directly under headings. Include "what is X" definitions. These formats are preferred for AI-generated featured snippets.':
    'Pridėkite glaustus atsakymų paragrafus (40-60 žodžių) tiesiai po antraštėmis. Įtraukite „kas yra X" apibrėžimus. Šie formatai yra pirmenybiniai DI generuojamiems išskirtiniams fragmentams.',
  'Content is well-optimized for featured snippets':
    'Turinys gerai optimizuotas išskirtiniams fragmentams',
  'Use question-format headings (How, What, Why...) and provide direct, concise answers. Voice assistants prefer natural language Q&A formatting.':
    'Naudokite klausimų formato antraštes (Kaip, Kas, Kodėl...) ir pateikite tiesioginius, glaustus atsakymus. Balso asistentai teikia pirmenybę natūralios kalbos klausimų-atsakymų formatui.',
  'Content is well-optimized for voice search':
    'Turinys gerai optimizuotas balso paieškai',
  'Diversify answer formats: add comparison tables, numbered steps, FAQ sections, and ordered lists. AI engines select different formats for different query types.':
    'Įvairinkite atsakymų formatus: pridėkite palyginimo lenteles, sunumeruotus žingsnius, DUK skyrius ir sunumeruotus sąrašus. DI varikliai pasirenka skirtingus formatus skirtingiems užklausų tipams.',
  'Good diversity of answer formats':
    'Gera atsakymų formatų įvairovė',
  'Add diverse schema types: FAQPage, HowTo, Article, Product, BreadcrumbList. Each schema type enables different AI answer formats.':
    'Pridėkite įvairius schemos tipus: FAQPage, HowTo, Article, Product, BreadcrumbList. Kiekvienas schemos tipas įgalina skirtingus DI atsakymų formatus.',
  'Schema markup diversity is strong':
    'Schemos žymėjimo įvairovė stipri',
};

/** Map of audit item details patterns → Lithuanian translations */
const ITEM_DETAILS_LT: Record<string, string> = {
  'No robots.txt found': 'robots.txt nerastas',
  'robots.txt exists but has no AI crawler directives': 'robots.txt egzistuoja, bet neturi DI robotų direktyvų',
  'No sitemap.xml found': 'sitemap.xml nerastas',
  'No llms.txt found': 'llms.txt nerastas',
  'No llms-full.txt found': 'llms-full.txt nerastas',
  'No JSON-LD structured data found on any page': 'Jokiame puslapyje nerasta JSON-LD struktūrinių duomenų',
  'No ai.txt or ai.json found': 'ai.txt arba ai.json nerasti',
  'No security.txt found': 'security.txt nerastas',
  'No TDM reservation found': 'TDM rezervacija nerasta',
  'TDM reservation found': 'TDM rezervacija rasta',
  'Web manifest found': 'Žiniatinklio manifestas rastas',
  'No web manifest found': 'Žiniatinklio manifestas nerastas',
  'humans.txt found': 'humans.txt rastas',
  'No humans.txt found': 'humans.txt nerastas',
  'No FAQ content detected on any page': 'Jokiame puslapyje neaptikta DUK turinio',
  'No AI crawlers are blocked in robots.txt': 'Jokie DI robotai nėra blokuojami robots.txt',
  'No max-snippet or max-image-preview directives found': 'Nerasta max-snippet arba max-image-preview direktyvų',
  'No indexing signals found': 'Nerasta indeksavimo signalų',
  'No images found on crawled pages': 'Nuskaitytuose puslapiuose nerasta paveikslėlių',
  'All pages served over HTTPS': 'Visi puslapiai aptarnaujami per HTTPS',
  'No content pages found': 'Nerasta turinio puslapių',
  'No content pages (>200 words) found to assess': 'Nerasta turinio puslapių (>200 žodžių) vertinimui',
};

/** Client-facing action guides — professional, specific instructions per item */
const CLIENT_ACTION_GUIDES: Record<string, { en: string; lt: string }> = {
  'Server-side Rendering': {
    en: 'Some of your pages rely on JavaScript to display content. AI crawlers (GPTBot, ClaudeBot, etc.) cannot execute JavaScript and will see blank pages. Work with your developer to enable server-side rendering (SSR) or static site generation (SSG) so that all page content is present in the initial HTML.',
    lt: 'Kai kurie jūsų puslapiai naudoja JavaScript turiniui rodyti. DI robotai (GPTBot, ClaudeBot ir kt.) negali vykdyti JavaScript ir mato tuščius puslapius. Dirbkite su savo programuotoju, kad įgalintumėte serverio pusės atvaizdavimą (SSR) arba statinį svetainės generavimą (SSG), kad visas turinys būtų pradiniame HTML.',
  },
  'Meta Descriptions': {
    en: 'Many pages are missing meta descriptions — the short summary that appears in search results. AI engines use these as the primary source for citations and snippets. Add a unique, descriptive <meta name="description"> tag (50-160 characters) to every page, clearly explaining what that page offers.',
    lt: 'Daugelyje puslapių trūksta meta aprašymų — trumpos santraukos, kuri rodoma paieškos rezultatuose. DI varikliai tai naudoja kaip pagrindinį šaltinį citavimui. Pridėkite unikalią, aprašomąją <meta name="description"> žymą (50-160 simbolių) kiekvienam puslapiui, aiškiai paaiškindami, ką tas puslapis siūlo.',
  },
  'Heading Hierarchy': {
    en: 'Your pages have inconsistent heading structure — skipped levels (e.g. H1 jumping to H3) or multiple H1 tags. AI models parse headings to understand content structure. Ensure every page has exactly one H1 (the page title), followed by H2 sections, H3 subsections, etc. — no skipped levels.',
    lt: 'Jūsų puslapiuose yra nenuosekli antraščių struktūra — praleisti lygiai (pvz., H1 šoka prie H3) arba kelios H1 žymės. DI modeliai analizuoja antraštes, kad suprastų turinio struktūrą. Įsitikinkite, kad kiekvienas puslapis turi tiksliai vieną H1 (puslapio pavadinimą), po kurio seka H2 skyriai, H3 poskyriai ir t.t. — be praleistų lygių.',
  },
  'Content Freshness': {
    en: 'None of your pages have date signals (published date, modified date). AI engines prioritize fresh content — AI-cited pages are on average 25.7% more recent than traditional search results. Add visible publication/update dates to your pages and include datePublished/dateModified in your JSON-LD structured data.',
    lt: 'Jokiame jūsų puslapyje nėra datos signalų (publikavimo datos, pakeitimo datos). DI varikliai teikia pirmenybę naujam turiniui — DI cituojami puslapiai yra vidutiniškai 25,7% naujesni nei tradiciniai paieškos rezultatai. Pridėkite matomas publikavimo/atnaujinimo datas ir įtraukite datePublished/dateModified į JSON-LD struktūrinius duomenis.',
  },
  'Content Structure & Depth': {
    en: 'Most of your pages have thin content (under 300 words). AI engines need substantive text to generate accurate citations. Expand key service and product pages to 500+ words with clear heading structure (at least 3 headings). Include detailed descriptions of your services, processes, pricing information, and answers to common customer questions.',
    lt: 'Dauguma jūsų puslapių turi mažai turinio (mažiau nei 300 žodžių). DI varikliams reikia išsamaus teksto tiksliam citavimui. Išplėskite pagrindinius paslaugų ir produktų puslapius iki 500+ žodžių su aiškia antraščių struktūra (bent 3 antraštės). Įtraukite išsamius paslaugų aprašymus, procesų paaiškinimus, kainų informaciją ir atsakymus į dažnus klientų klausimus.',
  },
  'Open Graph Tags': {
    en: 'Not all pages have Open Graph (og:title, og:description) tags. These control how your pages appear when shared on social media and are used by AI engines for rich previews. Add og:title, og:description, and og:image to every page\'s <head> section.',
    lt: 'Ne visi puslapiai turi Open Graph (og:title, og:description) žymes. Jos kontroliuoja, kaip jūsų puslapiai atrodo dalinantis socialiniuose tinkluose ir yra naudojamos DI variklių turtingiems peržiūroms. Pridėkite og:title, og:description ir og:image į kiekvieno puslapio <head> sekciją.',
  },
  'AI Content Directives': {
    en: 'Your pages don\'t include AI content directives. Add this meta tag to every page to explicitly allow AI engines to use your full content in their responses: <meta name="robots" content="max-snippet:-1, max-image-preview:large">. Without this, some AI engines may truncate or skip your content.',
    lt: 'Jūsų puslapiuose nėra DI turinio direktyvų. Pridėkite šią meta žymą į kiekvieną puslapį, kad aiškiai leistumėte DI varikliams naudoti visą jūsų turinį savo atsakymuose: <meta name="robots" content="max-snippet:-1, max-image-preview:large">. Be to, kai kurie DI varikliai gali sutrumpinti arba praleisti jūsų turinį.',
  },
  'FAQ Content': {
    en: 'No FAQ content was detected on your site. FAQ pages have the highest AI citation probability of any content type. Create a dedicated FAQ page (or FAQ sections on key service pages) with real questions your customers ask and detailed answers. We will automatically generate FAQPage JSON-LD schema for detected FAQ content.',
    lt: 'Jūsų svetainėje nerasta DUK turinio. DUK puslapiai turi didžiausią DI citavimo tikimybę iš visų turinio tipų. Sukurkite atskirą DUK puslapį (arba DUK skyrius pagrindiniuose paslaugų puslapiuose) su tikrais klausimais, kuriuos užduoda jūsų klientai, ir išsamiais atsakymais. Mes automatiškai sugeneruosime FAQPage JSON-LD schemą aptiktam DUK turiniui.',
  },
  'Title Tags': {
    en: 'Some pages are missing title tags, have duplicate titles, or titles outside the optimal 30-70 character range. Each page should have a unique, descriptive title that includes the primary keyword near the beginning. Good titles improve click-through rates from search results and help AI models identify page topics.',
    lt: 'Kai kuriuose puslapiuose trūksta pavadinimo žymų, yra pasikartojančių pavadinimų arba pavadinimų ilgis neatitinka optimalaus 30-70 simbolių diapazono. Kiekvienas puslapis turi turėti unikalų, aprašomąjį pavadinimą su pagrindiniu raktažodžiu pradžioje. Geri pavadinimai pagerina paspaudimų rodiklį paieškos rezultatuose ir padeda DI modeliams atpažinti puslapio temas.',
  },
  'Image Alt Text': {
    en: 'Many images on your site are missing alt text. Alt text provides a text description of images for search engines, screen readers, and AI models that cannot process images directly. Add concise, descriptive alt text to every image describing what the image shows.',
    lt: 'Daugelyje jūsų svetainės paveikslėlių trūksta alt teksto. Alt tekstas suteikia tekstinį paveikslėlių aprašymą paieškos varikliams, ekrano skaitytuvams ir DI modeliams, kurie negali tiesiogiai apdoroti paveikslėlių. Pridėkite glaustą, aprašomąjį alt tekstą kiekvienam paveikslėliui, apibūdinantį tai, kas vaizduojama.',
  },
  'Internal Linking': {
    en: 'Your site has weak internal linking — some pages are orphaned (no other page links to them) or pages have too few internal links. Add contextual links between related pages to help search engines discover all your content and understand topic relationships. Aim for at least 3-5 internal links per page.',
    lt: 'Jūsų svetainėje silpnas vidinis susiejimas — kai kurie puslapiai yra „našlaičiai" (joks kitas puslapis į juos nenurodo) arba puslapiuose per mažai vidinių nuorodų. Pridėkite kontekstinius ryšius tarp susijusių puslapių, kad padėtumėte paieškos varikliams aptikti visą jūsų turinį ir suprasti temų ryšius. Siekite bent 3-5 vidinių nuorodų puslapyje.',
  },
  'Search Engine Indexing': {
    en: `Your site is missing key search engine indexing signals. Without these, search engines and AI crawlers may not discover your content. Here's what to do:

<strong>1. Google Search Console</strong> — Go to <a href="https://search.google.com/search-console/">search.google.com/search-console</a>, add your site, and verify ownership. Google will provide a <code>&lt;meta name="google-site-verification"&gt;</code> tag to add to your homepage. This gives you access to indexing status, search analytics, and the ability to request URL indexing.

<strong>2. Bing Webmaster Tools</strong> — Go to <a href="https://www.bing.com/webmasters/">bing.com/webmasters</a> and add your site. Verify with the <code>&lt;meta name="msvalidate.01"&gt;</code> tag. Bing also powers DuckDuckGo, Yahoo, and Ecosia — one registration covers multiple engines.

<strong>3. IndexNow for Instant Indexing</strong> — Implement the <a href="https://www.indexnow.org/">IndexNow protocol</a> to notify search engines immediately when you publish or update content. Generate an API key, host it at <code>/[key].txt</code>, and ping the IndexNow API on each content change. Supported by Bing, Yandex, Seznam, and Naver.

<strong>4. Quick Backlink Opportunities</strong> — Create profiles linking to your site on: GitHub (organization profile), LinkedIn (company page), Twitter/X (bio link), Product Hunt, Crunchbase, and relevant industry directories. Each quality backlink signals to search engines that your site is legitimate and worth indexing.

<strong>Expected Timeline:</strong> After setting up GSC and submitting your sitemap, initial indexing typically takes 2-7 days. Full indexing of all pages may take 2-4 weeks depending on site size and crawl frequency.`,
    lt: `Jūsų svetainėje trūksta pagrindinių paieškos variklių indeksavimo signalų. Be jų paieškos varikliai ir DI robotai gali neaptikti jūsų turinio. Štai ką daryti:

<strong>1. Google Search Console</strong> — Eikite į <a href="https://search.google.com/search-console/">search.google.com/search-console</a>, pridėkite savo svetainę ir patvirtinkite nuosavybę. Google pateiks <code>&lt;meta name="google-site-verification"&gt;</code> žymą, kurią reikia pridėti į pagrindinį puslapį. Tai suteikia prieigą prie indeksavimo būsenos, paieškos analitikos ir galimybę prašyti URL indeksavimo.

<strong>2. Bing Webmaster Tools</strong> — Eikite į <a href="https://www.bing.com/webmasters/">bing.com/webmasters</a> ir pridėkite savo svetainę. Patvirtinkite su <code>&lt;meta name="msvalidate.01"&gt;</code> žyma. Bing taip pat maitina DuckDuckGo, Yahoo ir Ecosia — viena registracija apima kelis variklius.

<strong>3. IndexNow greitam indeksavimui</strong> — Įdiekite <a href="https://www.indexnow.org/">IndexNow protokolą</a>, kad iš karto praneštumėte paieškos varikliams, kai publikuojate ar atnaujinate turinį. Sugeneruokite API raktą, patalpinkite jį <code>/[raktas].txt</code> ir siųskite užklausą IndexNow API kiekvieno turinio pakeitimo metu.

<strong>4. Greitos nuorodų galimybės</strong> — Sukurkite profilius su nuorodomis į savo svetainę: GitHub (organizacijos profilis), LinkedIn (įmonės puslapis), Twitter/X (bio nuoroda), Product Hunt, Crunchbase ir atitinkami pramonės katalogai. Kiekviena kokybiška nuoroda signalizuoja paieškos varikliams, kad jūsų svetainė yra teisėta ir verta indeksavimo.

<strong>Numatomas laikas:</strong> Nustačius GSC ir pateikus sitemap, pradinis indeksavimas paprastai užtrunka 2-7 dienas. Visų puslapių indeksavimas gali užtrukti 2-4 savaites, priklausomai nuo svetainės dydžio.`,
  },
};

// E-E-A-T action guides
CLIENT_ACTION_GUIDES['Author & Expertise Signals'] = {
  en: 'Your content pages lack author attribution. Add author names with bylines and author bio sections that highlight credentials, experience, and expertise. AI engines evaluate E-E-A-T (Experience, Expertise, Authoritativeness, Trust) signals — pages with clear author expertise rank higher in AI citations.',
  lt: 'Jūsų turinio puslapiuose trūksta autoriaus priskyrimo. Pridėkite autorių vardus su pasirašymais ir autoriaus biografijos sekcijas, kurios pabrėžia kvalifikacijas, patirtį ir kompetenciją. DI varikliai vertina E-E-A-T signalus — puslapiai su aiškia autoriaus kompetencija yra aukščiau DI citavime.',
};
CLIENT_ACTION_GUIDES['Trust Signals'] = {
  en: 'Your site is missing key trust signals. Add visible contact information (email, phone, physical address), create a dedicated About/Company page describing your organization, and ensure you have Privacy Policy and Terms of Service pages. These trust indicators are critical for AI engines evaluating your site\'s reliability.',
  lt: 'Jūsų svetainėje trūksta pagrindinių pasitikėjimo signalų. Pridėkite matomą kontaktinę informaciją (el. paštą, telefoną, fizinį adresą), sukurkite atskirą „Apie mus" puslapį aprašantį organizaciją ir įsitikinkite, kad turite Privatumo politikos ir Naudojimo sąlygų puslapius.',
};
CLIENT_ACTION_GUIDES['Social Proof & Authority'] = {
  en: 'Your site has limited social media presence. Add links to your social media profiles (LinkedIn, Facebook, Twitter/X, Instagram, YouTube, GitHub) in your site footer or contact page. Multiple verified platform profiles help AI engines confirm your entity identity and signal authority in your industry.',
  lt: 'Jūsų svetainėje ribota socialinių tinklų prezencija. Pridėkite nuorodas į socialinių tinklų profilius (LinkedIn, Facebook, Twitter/X, Instagram, YouTube, GitHub) svetainės poraštėje arba kontaktų puslapyje.',
};
CLIENT_ACTION_GUIDES['Citation Quality'] = {
  en: 'Your content lacks data-backed claims and source citations. Strengthen your content by adding statistics (e.g., "75% of users prefer..."), citing research studies and industry reports, including expert quotes, and linking to authoritative external sources. Well-cited content is significantly more likely to be used in AI-generated responses.',
  lt: 'Jūsų turinyje trūksta duomenimis pagrįstų teiginių ir šaltinių citavimo. Sustiprinkite turinį pridėdami statistiką (pvz., „75% vartotojų teikia pirmenybę..."), cituodami tyrimus ir pramonės ataskaitas, įtraukdami ekspertų citatas ir nuorodas į autoritetinius išorinius šaltinius.',
};
CLIENT_ACTION_GUIDES['Featured Snippet Readiness'] = {
  en: 'Your pages aren\'t optimized for featured snippets. Add concise answer paragraphs (40-60 words) directly under question headings. Include "what is X" definitions, step-by-step instructions, and comparison summaries. AI engines extract these paragraph-length answers for direct responses to user queries.',
  lt: 'Jūsų puslapiai nėra optimizuoti išskirtiniams fragmentams. Pridėkite glaustus atsakymų paragrafus (40-60 žodžių) tiesiai po klausimų antraštėmis. Įtraukite „kas yra X" apibrėžimus, žingsnis po žingsnio instrukcijas ir palyginimo santraukas.',
};
CLIENT_ACTION_GUIDES['Voice Search Optimization'] = {
  en: 'Your content isn\'t optimized for voice search. Use natural question-format headings like "How do I...", "What is...", "Why should...". Provide direct, concise answers (15-30 words) immediately after each question heading. Voice assistants read these short answer blocks aloud to users.',
  lt: 'Jūsų turinys nėra optimizuotas balso paieškai. Naudokite natūralias klausimų formato antraštes kaip „Kaip aš galiu...", „Kas yra...", „Kodėl turėčiau...". Pateikite tiesioginius, glaustus atsakymus (15-30 žodžių) iš karto po kiekvienos klausimo antraštės.',
};
CLIENT_ACTION_GUIDES['Answer Format Diversity'] = {
  en: 'Your site lacks diverse answer formats. AI engines select different content formats for different query types. Add: comparison tables (for "X vs Y" queries), numbered step lists (for "how to" queries), FAQ sections (for question queries), and definition paragraphs (for "what is" queries). This maximizes your chances of being featured across different AI response types.',
  lt: 'Jūsų svetainėje trūksta įvairių atsakymų formatų. DI varikliai pasirenka skirtingus turinio formatus skirtingiems užklausų tipams. Pridėkite: palyginimo lenteles, sunumeruotus žingsnių sąrašus, DUK skyrius ir apibrėžimų paragrafus.',
};
CLIENT_ACTION_GUIDES['Schema Markup Diversity'] = {
  en: 'Your site uses limited schema markup types. Add diverse JSON-LD schemas to enable different AI answer formats: FAQPage (for Q&A results), HowTo (for step-by-step results), Article/BlogPosting (for knowledge panels), Product (for shopping results), and BreadcrumbList (for navigation context). Each schema type opens a different AI citation pathway.',
  lt: 'Jūsų svetainė naudoja ribotus schemos žymėjimo tipus. Pridėkite įvairius JSON-LD schemas: FAQPage (klausimų-atsakymų rezultatams), HowTo (žingsnis po žingsnio rezultatams), Article/BlogPosting (žinių skydeliams), Product (apsipirkimo rezultatams) ir BreadcrumbList (navigacijos kontekstui).',
};

const TRANSLATIONS: Record<string, ReportStrings> = { en: STRINGS_EN, lt: STRINGS_LT };

function detectLanguage(crawlResult: SiteCrawlResult): string {
  const langCounts: Record<string, number> = {};
  for (const page of crawlResult.pages) {
    const lang = page.meta.language?.split('-')[0]?.toLowerCase();
    if (lang) langCounts[lang] = (langCounts[lang] || 0) + 1;
  }
  let topLang = 'en';
  let topCount = 0;
  for (const [lang, count] of Object.entries(langCounts)) {
    if (count > topCount) { topLang = lang; topCount = count; }
  }
  return topLang;
}

function t(strings: ReportStrings, key: keyof ReportStrings): string | string[] {
  return strings[key];
}

function getClientGuide(itemName: string, lang: string): string | null {
  const guide = CLIENT_ACTION_GUIDES[itemName];
  if (!guide) return null;
  return lang === 'lt' ? guide.lt : guide.en;
}

function translateItemName(name: string, lang: string): string {
  if (lang === 'lt') return ITEM_NAMES_LT[name] || name;
  return name;
}

function translateItemRec(rec: string, lang: string): string {
  if (lang === 'lt') return ITEM_RECS_LT[rec] || rec;
  return rec;
}

function translateItemDetails(details: string, lang: string): string {
  if (lang !== 'lt') return details;
  // Try exact match first
  if (ITEM_DETAILS_LT[details]) return ITEM_DETAILS_LT[details];
  // Try pattern-based translations for dynamic strings
  let translated = details;
  translated = translated.replace(/(\d+)\/(\d+) pages have server-rendered content/, '$1/$2 puslapių turi serverio pusės atvaizdavimą');
  translated = translated.replace(/(\d+)\/(\d+) pages have meta descriptions/, '$1/$2 puslapių turi meta aprašymus');
  translated = translated.replace(/(\d+)\/(\d+) pages with headings have correct/, '$1/$2 puslapių su antraštėmis turi teisingą');
  translated = translated.replace(/H1>H2>H3 hierarchy/, 'H1>H2>H3 hierarchiją');
  translated = translated.replace(/(\d+)\/(\d+) pages have OG title \+ description/, '$1/$2 puslapių turi OG pavadinimą + aprašymą');
  translated = translated.replace(/(\d+)\/(\d+) pages have date signals/, '$1/$2 puslapių turi datos signalus');
  translated = translated.replace(/updated within 12 months/, 'atnaujinta per 12 mėnesių');
  translated = translated.replace(/with JSON-LD dates/, 'su JSON-LD datomis');
  translated = translated.replace(/(\d+)\/(\d+) pages >500 words/, '$1/$2 puslapių >500 žodžių');
  translated = translated.replace(/well-structured/, 'gerai struktūruotų');
  translated = translated.replace(/thin pages/, 'plonas puslapis(-iai)');
  translated = translated.replace(/(\d+) FAQ items on (\d+) pages/, '$1 DUK elementų $2 puslapiuose');
  translated = translated.replace(/with FAQPage schema/, 'su FAQPage schema');
  translated = translated.replace(/no FAQPage schema/, 'be FAQPage schemos');
  translated = translated.replace(/Sitemap contains (\d+) URLs/, 'Sitemap turi $1 URL adresų');
  translated = translated.replace(/with lastmod dates/, 'su lastmod datomis');
  translated = translated.replace(/no lastmod/, 'be lastmod');
  translated = translated.replace(/Crawled (\d+) pages/, 'Nuskaityta $1 puslapių');
  translated = translated.replace(/robots\.txt mentions (\d+)\/(\d+) key AI crawlers/, 'robots.txt mini $1/$2 pagrindinius DI robotus');
  translated = translated.replace(/max-snippet on (\d+) pages/, 'max-snippet $1 puslapiuose');
  translated = translated.replace(/max-image-preview on (\d+) pages/, 'max-image-preview $1 puslapiuose');
  translated = translated.replace(/>50 words without JS/, '>50 žodžių be JS');
  translated = translated.replace(/>=30 chars/, '>=30 simbolių');
  translated = translated.replace(/Indexing signals found:/, 'Indeksavimo signalai rasti:');
  translated = translated.replace(/No indexing signals found\. Missing:/, 'Nerasta indeksavimo signalų. Trūksta:');
  translated = translated.replace(/\. Missing:/, '. Trūksta:');
  translated = translated.replace(/Google Search Console verification/, 'Google Search Console patvirtinimas');
  translated = translated.replace(/Bing Webmaster Tools verification/, 'Bing Webmaster Tools patvirtinimas');
  translated = translated.replace(/Sitemap in robots\.txt/, 'Sitemap robots.txt faile');
  translated = translated.replace(/No noindex pages/, 'Nėra noindex puslapių');
  translated = translated.replace(/page\(s\) with noindex/, 'puslapis(-iai) su noindex');
  translated = translated.replace(/Bing Webmaster Tools verification \(([^)]+)\)/, 'Bing Webmaster Tools patvirtinimas ($1)');
  translated = translated.replace(/Bing Webmaster Tools verification \(meta tag or BingSiteAuth\.xml\)/, 'Bing Webmaster Tools patvirtinimas (meta žyma arba BingSiteAuth.xml)');
  translated = translated.replace(/Canonical URLs set/, 'Canonical URL nustatyti');
  translated = translated.replace(/Canonical URLs on only/, 'Canonical URL tik');
  translated = translated.replace(/No canonical URLs set/, 'Canonical URL nenustatyti');
  translated = translated.replace(/(\d+)\/(\d+) pages\)/, '$1/$2 puslapių)');
  // SEO detail patterns
  translated = translated.replace(/(\d+)\/(\d+) pages have titles/, '$1/$2 puslapių turi pavadinimus');
  translated = translated.replace(/with optimal length/, 'su optimaliuoju ilgiu');
  translated = translated.replace(/duplicate titles/, 'pasikartojančių pavadinimų');
  translated = translated.replace(/(\d+)\/(\d+) images have alt text/, '$1/$2 paveikslėlių turi alt tekstą');
  translated = translated.replace(/Avg ([\d.]+) internal links\/page/, 'Vid. $1 vidinių nuorodų/puslapyje');
  translated = translated.replace(/orphan pages \(no inbound links\)/, 'našlaičių puslapių (be įeinančių nuorodų)');
  translated = translated.replace(/(\d+)\/(\d+) pages have a viewport meta tag/, '$1/$2 puslapių turi viewport meta žymą');
  translated = translated.replace(/(\d+)\/(\d+) pages use HTTPS/, '$1/$2 puslapių naudoja HTTPS');
  translated = translated.replace(/All (\d+) crawled pages returned successful status codes/, 'Visi $1 nuskaityti puslapiai grąžino sėkmingus būsenos kodus');
  translated = translated.replace(/(\d+)\/(\d+) pages returned error status codes/, '$1/$2 puslapių grąžino klaidų būsenos kodus');
  return translated;
}

function translateCategory(category: string, lang: string): string {
  if (lang !== 'lt') return category;
  const map: Record<string, string> = {
    critical: 'kritinis',
    high: 'aukštas',
    medium: 'vidutinis',
    low: 'žemas',
    seo: 'seo',
    eeat: 'e-e-a-t',
    aeo: 'aeo',
  };
  return map[category] || category;
}

function renderAffectedUrls(item: AuditItem, index: number, s: ReportStrings): string {
  if (!item.affectedUrls || item.affectedUrls.length === 0) return '';
  const id = `affected-urls-${index}`;
  return `
        <button class="affected-urls-toggle" onclick="toggleUrls('${id}', this)">
          <span class="arrow">&#9654;</span> ${s.affectedPagesLabel} (${item.affectedUrls.length})
        </button>
        <ul class="affected-urls-list" id="${id}">
          ${item.affectedUrls.map(url => `<li><a href="${url}" target="_blank" rel="noopener">${url}</a></li>`).join('\n          ')}
        </ul>`;
}

export function generateAuditReportHtml(
  audit: AuditResult,
  crawlResult: SiteCrawlResult,
): string {
  const { domain, baseUrl, crawlStats, siteIdentity, pages } = crawlResult;
  const siteName = siteIdentity.name || domain;
  const gradeColor = getGradeColor(audit.grade);
  const logoSrc = siteIdentity.logoUrl || siteIdentity.faviconUrl;
  const clientActionItems = getClientActionItems(audit);
  const lang = detectLanguage(crawlResult);
  const s = TRANSLATIONS[lang] || STRINGS_EN;

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${s.title} — ${siteName}</title>
  <style>
    :root {
      --bg: #09090b;
      --surface: #131316;
      --surface2: #1c1c22;
      --surface3: #25252d;
      --border: rgba(255,255,255,0.06);
      --border-strong: rgba(255,255,255,0.1);
      --text: #ececf1;
      --text-dim: #a1a1aa;
      --text-muted: #71717a;
      --accent: #818cf8;
      --green: #34d399;
      --yellow: #fbbf24;
      --red: #f87171;
      --blue: #60a5fa;
      --shadow-sm: 0 1px 2px rgba(0,0,0,0.3), 0 1px 3px rgba(0,0,0,0.15);
      --shadow-md: 0 4px 12px rgba(0,0,0,0.4), 0 2px 4px rgba(0,0,0,0.2);
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem;
      max-width: 1200px;
      margin: 0 auto;
    }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; letter-spacing: -0.025em; }
    h2 {
      font-size: 1.4rem;
      margin: 2rem 0 1rem;
      color: var(--text);
      position: relative;
      padding-left: 1rem;
      letter-spacing: -0.02em;
    }
    h2::before {
      content: '';
      position: absolute;
      left: 0;
      top: 0.15em;
      bottom: 0.15em;
      width: 3px;
      border-radius: 2px;
      background: var(--accent);
    }
    h3 { font-size: 1.1rem; margin-bottom: 0.5rem; letter-spacing: -0.01em; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 2rem;
      padding-bottom: 2rem;
      border-bottom: 1px solid var(--border);
    }
    .header-info { flex: 1; }
    .header-info p { color: var(--text-dim); margin: 0.25rem 0; }
    .grade-circle {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      box-shadow: inset 0 0 0 4px ${gradeColor}, 0 0 20px ${gradeColor}44, 0 0 40px ${gradeColor}22;
      flex-shrink: 0;
      margin-left: 2rem;
    }
    .grade-letter { font-size: 2.5rem; font-weight: 700; color: ${gradeColor}; }
    .grade-score { font-size: 0.9rem; color: var(--text-dim); }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1rem;
      margin-bottom: 2rem;
    }
    .stat-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 1.25rem;
      box-shadow: var(--shadow-sm);
      transition: border-color 0.2s ease;
    }
    .stat-card:hover { border-color: var(--border-strong); }
    .stat-card .label { font-size: 0.7rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; }
    .stat-card .value { font-size: 1.75rem; font-weight: 700; margin-top: 0.25rem; letter-spacing: -0.02em; }
    .category-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin: 1.5rem 0 0.75rem;
      padding-bottom: 0.75rem;
      border-bottom: 1px solid var(--border);
    }
    .category-badge {
      font-size: 0.7rem;
      text-transform: uppercase;
      padding: 2px 8px;
      border-radius: 4px;
      font-weight: 600;
      letter-spacing: 0.03em;
    }
    .badge-critical { background: rgba(248,113,113,0.12); color: var(--red); }
    .badge-high { background: rgba(251,191,36,0.12); color: var(--yellow); }
    .badge-medium { background: rgba(96,165,250,0.12); color: var(--blue); }
    .badge-low { background: rgba(161,161,170,0.12); color: var(--text-dim); }
    .badge-seo { background: rgba(45,212,191,0.12); color: #2dd4bf; }
    .badge-eeat { background: rgba(168,85,247,0.12); color: #a855f7; }
    .badge-aeo { background: rgba(236,72,153,0.12); color: #ec4899; }
    .audit-item {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 1rem 1.25rem;
      margin-bottom: 0.75rem;
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      box-shadow: var(--shadow-sm);
      transition: box-shadow 0.2s ease, border-color 0.2s ease;
    }
    .audit-item:hover { box-shadow: var(--shadow-md); border-color: var(--border-strong); }
    .status-icon {
      width: 28px;
      height: 28px;
      border-radius: 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.9rem;
      flex-shrink: 0;
      margin-top: 2px;
    }
    .status-pass { background: rgba(52,211,153,0.12); color: var(--green); }
    .status-partial { background: rgba(251,191,36,0.12); color: var(--yellow); }
    .status-fail { background: rgba(248,113,113,0.12); color: var(--red); }
    .item-content { flex: 1; }
    .item-name { font-weight: 600; margin-bottom: 0.25rem; }
    .item-details { font-size: 0.85rem; color: var(--text-dim); margin-bottom: 0.25rem; }
    .item-rec { font-size: 0.85rem; color: var(--accent); }
    .score-bar {
      width: 120px;
      height: 8px;
      background: var(--surface2);
      border-radius: 4px;
      overflow: hidden;
      margin-top: 8px;
      flex-shrink: 0;
    }
    .score-fill { height: 100%; border-radius: 4px; }
    .files-section {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1.5rem;
      margin-top: 2rem;
      box-shadow: var(--shadow-sm);
    }
    .file-list { list-style: none; }
    .file-list li {
      padding: 0.5rem 0;
      border-bottom: 1px solid var(--border);
      display: flex;
      justify-content: space-between;
      font-size: 0.9rem;
    }
    .file-list li:last-child { border-bottom: none; }
    .file-list code {
      font-family: 'SF Mono', SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
      background: var(--surface2);
      padding: 0.15rem 0.5rem;
      border-radius: 4px;
      font-size: 0.85rem;
    }
    .file-status { font-size: 0.8rem; }
    .existing { color: var(--green); }
    .generated { color: var(--accent); }
    .site-logo {
      width: 48px;
      height: 48px;
      border-radius: 10px;
      object-fit: contain;
      background: var(--surface2);
      padding: 4px;
      flex-shrink: 0;
    }
    .header-top {
      display: flex;
      align-items: center;
      gap: 1rem;
      margin-bottom: 0.25rem;
    }
    .action-items {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1.5rem;
      margin-top: 2rem;
      box-shadow: var(--shadow-sm);
    }
    .action-items .intro {
      color: var(--text-dim);
      font-size: 0.9rem;
      margin-bottom: 1.25rem;
      line-height: 1.6;
    }
    .action-item {
      display: flex;
      gap: 1rem;
      padding: 1rem;
      margin-bottom: 0.75rem;
      background: var(--surface2);
      border: 1px solid var(--border);
      border-radius: 10px;
      border-left: 3px solid var(--yellow);
    }
    .action-item.action-fail {
      border-left-color: var(--red);
    }
    .action-num {
      width: 28px;
      height: 28px;
      border-radius: 8px;
      background: rgba(251,191,36,0.12);
      color: var(--yellow);
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 0.8rem;
      flex-shrink: 0;
    }
    .action-fail .action-num {
      background: rgba(248,113,113,0.12);
      color: var(--red);
    }
    .action-body { flex: 1; }
    .action-title { font-weight: 600; margin-bottom: 0.25rem; }
    .action-desc { font-size: 0.85rem; color: var(--text-dim); line-height: 1.5; }
    .action-score {
      font-size: 0.75rem;
      color: var(--text-muted);
      margin-top: 0.35rem;
    }
    .affected-urls-toggle {
      display: inline-flex;
      align-items: center;
      gap: 0.35rem;
      margin-top: 0.5rem;
      padding: 4px 10px;
      border-radius: 6px;
      border: 1px solid var(--border);
      background: var(--surface3);
      color: var(--text-dim);
      font-size: 0.75rem;
      cursor: pointer;
      font-family: inherit;
      transition: border-color 0.15s ease, color 0.15s ease;
    }
    .affected-urls-toggle:hover { border-color: var(--accent); color: var(--accent); }
    .affected-urls-toggle .arrow { transition: transform 0.2s ease; display: inline-block; }
    .affected-urls-toggle.open .arrow { transform: rotate(90deg); }
    .affected-urls-list {
      display: none;
      margin-top: 0.5rem;
      padding: 0.5rem 0.75rem;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      list-style: none;
      max-height: 200px;
      overflow-y: auto;
    }
    .affected-urls-list.open { display: block; }
    .affected-urls-list li {
      padding: 3px 0;
      font-size: 0.8rem;
      color: var(--text-dim);
      border-bottom: 1px solid var(--border);
    }
    .affected-urls-list li:last-child { border-bottom: none; }
    .affected-urls-list a { color: var(--accent); font-size: 0.8rem; word-break: break-all; }
    .priority-fixes { margin-top: 2rem; }
    .priority-fix-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 1rem 1.25rem;
      margin-bottom: 0.75rem;
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      border-left: 3px solid var(--accent);
      box-shadow: var(--shadow-sm);
      transition: box-shadow 0.2s ease, border-color 0.2s ease;
    }
    .priority-fix-card:hover { box-shadow: var(--shadow-md); border-color: var(--border-strong); }
    .priority-impact {
      display: flex;
      flex-direction: column;
      align-items: center;
      min-width: 60px;
      flex-shrink: 0;
    }
    .priority-impact-value {
      font-size: 1.4rem;
      font-weight: 700;
      color: var(--green);
      line-height: 1;
    }
    .priority-impact-label {
      font-size: 0.65rem;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.03em;
      margin-top: 2px;
    }
    .priority-fix-body { flex: 1; }
    .priority-fix-title { font-weight: 600; margin-bottom: 0.25rem; display: flex; align-items: center; gap: 0.5rem; }
    .priority-fix-rec { font-size: 0.85rem; color: var(--text-dim); line-height: 1.5; }
    .effort-pill {
      display: inline-block;
      padding: 1px 8px;
      border-radius: 10px;
      font-size: 0.7rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }
    .effort-easy { background: rgba(52,211,153,0.15); color: var(--green); }
    .effort-medium { background: rgba(251,191,36,0.15); color: var(--yellow); }
    .effort-hard { background: rgba(248,113,113,0.15); color: var(--red); }
    .footer {
      margin-top: 3rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--border);
      font-size: 0.8rem;
      color: var(--text-muted);
      text-align: center;
      letter-spacing: 0.01em;
    }
    .export-toolbar {
      position: sticky; top: 0; z-index: 50;
      background: rgba(19,19,22,0.75);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border-bottom: 1px solid var(--border);
      padding: 10px 16px; margin: -2rem -2rem 2rem -2rem;
      display: flex; gap: 10px; align-items: center;
    }
    .export-toolbar button {
      padding: 6px 16px; border-radius: 6px; border: 1px solid var(--border-strong);
      background: var(--accent); color: white; font-weight: 500; font-size: 13px;
      cursor: pointer; font-family: inherit;
      transition: opacity 0.15s ease, transform 0.15s ease;
    }
    .export-toolbar button:hover { opacity: 0.85; transform: translateY(-1px); }
    .export-toolbar button.secondary { background: var(--surface2); color: var(--text); }
    .export-toolbar span { color: var(--text-muted); font-size: 13px; margin-left: auto; }
    @media print {
      .export-toolbar { display: none !important; }
      :root {
        --bg: #fff; --surface: #fff; --surface2: #f5f5f5; --surface3: #eee;
        --border: #ddd; --border-strong: #ccc;
        --text: #111; --text-dim: #555; --text-muted: #777;
        --shadow-sm: none; --shadow-md: none;
      }
      body { background: #fff; color: #111; padding: 1rem; }
      h2::before { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .grade-circle { -webkit-print-color-adjust: exact; print-color-adjust: exact; box-shadow: inset 0 0 0 4px currentColor !important; }
      .score-fill, .status-icon, .category-badge { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .stat-card { border-color: #ddd; }
      .audit-item { break-inside: avoid; box-shadow: none; }
      .affected-urls-toggle { display: none !important; }
      .affected-urls-list { display: block !important; border-color: #ddd; }
    }
  </style>
</head>
<body>
  <div class="export-toolbar">
    <button onclick="window.print()">${s.downloadPdf}</button>
    <button class="secondary" onclick="exportCsv()">${s.exportCsv}</button>
    <span>${s.exportHint}</span>
  </div>
  <div class="header">
    <div class="header-info">
      <div class="header-top">
        ${logoSrc ? `<img class="site-logo" src="${logoSrc}" alt="${siteName} logo" onerror="this.style.display='none'">` : ''}
        <h1>${s.title}</h1>
      </div>
      <p><strong>${siteName}</strong> &mdash; <a href="${baseUrl}">${baseUrl}</a></p>
      <p>${s.generated}: ${new Date().toISOString().split('T')[0]} | ${s.pagesCrawled}: ${crawlStats.totalPages} | ${s.time}: ${(crawlStats.totalTime / 1000).toFixed(1)}s</p>
    </div>
    <div class="grade-circle">
      <span class="grade-letter">${audit.grade}</span>
      <span class="grade-score">${audit.overallScore}/100</span>
    </div>
  </div>

  <div class="stats-grid">
    <div class="stat-card">
      <div class="label">${s.overallScore}</div>
      <div class="value" style="color:${gradeColor}">${audit.overallScore}%</div>
    </div>
    <div class="stat-card">
      <div class="label">${s.criticalChecks}</div>
      <div class="value">${audit.summary.critical.passed}/${audit.summary.critical.total}</div>
    </div>
    <div class="stat-card">
      <div class="label">${s.highPriority}</div>
      <div class="value">${audit.summary.high.passed}/${audit.summary.high.total}</div>
    </div>
    <div class="stat-card">
      <div class="label">${s.seoChecks}</div>
      <div class="value">${audit.summary.seo.passed}/${audit.summary.seo.total}</div>
    </div>
    <div class="stat-card">
      <div class="label">${s.eeatChecks}</div>
      <div class="value">${audit.summary.eeat.passed}/${audit.summary.eeat.total}</div>
    </div>
    <div class="stat-card">
      <div class="label">${s.aeoChecks}</div>
      <div class="value">${audit.summary.aeo.passed}/${audit.summary.aeo.total}</div>
    </div>
    <div class="stat-card">
      <div class="label">${s.pagesCrawledLabel}</div>
      <div class="value">${crawlStats.totalPages}</div>
    </div>
  </div>

  <h2>${s.auditResults}</h2>

${renderCategory(s.critical, 'critical', audit.items, lang)}
${renderCategory(s.high, 'high', audit.items, lang)}
${renderCategory(s.medium, 'medium', audit.items, lang)}
${renderCategory(s.low, 'low', audit.items, lang)}
${renderCategory(s.seo, 'seo', audit.items, lang)}
${renderCategory(s.eeat, 'eeat', audit.items, lang)}
${renderCategory(s.aeo, 'aeo', audit.items, lang)}

${renderPriorityFixes(audit, lang)}

${clientActionItems.length > 0 ? `
  <div class="action-items">
    <h2 style="margin-top:0">${s.actionItemsTitle}</h2>
    <p class="intro">${s.actionItemsIntro}</p>
${clientActionItems.map((item, i) => {
    const guide = getClientGuide(item.name, lang) || translateItemRec(item.recommendation, lang);
    return `    <div class="action-item${item.status === 'fail' ? ' action-fail' : ''}">
      <div class="action-num">${i + 1}</div>
      <div class="action-body">
        <div class="action-title">${translateItemName(item.name, lang)}</div>
        <div class="action-desc">${guide}</div>
        <div class="action-score">${s.actionCurrentScore}: ${item.score}/${item.maxScore} &middot; ${s.actionPriority}: ${translateCategory(item.category, lang)}</div>${renderAffectedUrls(item, i, s)}
      </div>
    </div>`;
  }).join('\n')}
  </div>
` : ''}
  <div class="files-section">
    <h2 style="margin-top:0">${s.generatedFiles}</h2>
    <p style="color:var(--text-dim);margin-bottom:1rem">${s.generatedFilesDesc}</p>
    <ul class="file-list">
      <li><code>llms.txt</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>llms-full.txt</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>robots.txt</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>sitemap.xml</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>ai.txt</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>ai.json</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>.well-known/security.txt</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>.well-known/tdmrep.json</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>humans.txt</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>manifest.json</code> <span class="generated">${s.generatedLabel}</span></li>
      <li><code>structured-data/*.json</code> <span class="generated">${s.generatedLabel}</span></li>
    </ul>
  </div>

  <div class="files-section">
    <h2 style="margin-top:0">${s.deployTitle}</h2>
    <ol style="padding-left:1.5rem;color:var(--text-dim)">
      ${(s.deploySteps as string[]).map(step => `<li>${step}</li>`).join('\n      ')}
    </ol>
  </div>

  <div class="footer">
    ${s.footer}
  </div>
<script>
function toggleUrls(id, btn) {
  var list = document.getElementById(id);
  var isOpen = list.classList.contains('open');
  list.classList.toggle('open');
  btn.classList.toggle('open');
}
function exportCsv() {
  const rows = [['Item','Category','Score','MaxScore','Status','Details','Recommendation']];
  document.querySelectorAll('.audit-item').forEach(el => {
    const name = el.querySelector('.item-name')?.textContent || '';
    const details = el.querySelector('.item-details')?.textContent || '';
    const rec = el.querySelector('.item-rec')?.textContent || '';
    const scoreText = el.querySelector('[style*="text-align:right"]')?.textContent || '';
    const [score, maxScore] = scoreText.split('/');
    const cat = el.closest('.category-header ~ *') ? '' : '';
    const statusEl = el.querySelector('.status-icon');
    const status = statusEl?.classList.contains('status-pass') ? 'pass' : statusEl?.classList.contains('status-fail') ? 'fail' : 'partial';
    // Walk back to find category header
    let catText = '';
    let prev = el.previousElementSibling;
    while (prev) {
      if (prev.classList.contains('category-header')) { catText = prev.querySelector('.category-badge')?.textContent || ''; break; }
      prev = prev.previousElementSibling;
    }
    rows.push([name, catText, score?.trim() || '', maxScore?.trim() || '', status, details, rec]);
  });
  const csv = rows.map(r => r.map(c => '"' + c.replace(/"/g, '""') + '"').join(',')).join('\\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'geo-audit-report.csv';
  a.click();
  URL.revokeObjectURL(a.href);
}
if (new URLSearchParams(location.search).get('export') === 'pdf') window.print();
if (new URLSearchParams(location.search).get('export') === 'csv') exportCsv();
</script>
</body>
</html>`;
}

function renderCategory(title: string, category: string, items: AuditItem[], lang: string): string {
  const filtered = items.filter(i => i.category === category);
  if (filtered.length === 0) return '';

  const badgeClass = `badge-${category}`;

  let html = `  <div class="category-header">
    <h3>${title}</h3>
    <span class="category-badge ${badgeClass}">${translateCategory(category, lang)}</span>
  </div>\n`;

  for (const item of filtered) {
    const statusIcon = item.status === 'pass' ? '&#10003;' : item.status === 'partial' ? '~' : '&#10005;';
    const statusClass = `status-${item.status === 'not_applicable' ? 'partial' : item.status}`;
    const fillColor = item.score >= 70 ? 'var(--green)' : item.score >= 40 ? 'var(--yellow)' : 'var(--red)';
    const gradientFrom = item.score >= 70 ? '#34d399' : item.score >= 40 ? '#fbbf24' : '#f87171';
    const gradientTo = item.score >= 70 ? '#6ee7b7' : item.score >= 40 ? '#fcd34d' : '#fca5a5';

    html += `  <div class="audit-item">
    <div class="status-icon ${statusClass}">${statusIcon}</div>
    <div class="item-content">
      <div class="item-name">${translateItemName(item.name, lang)}</div>
      <div class="item-details">${translateItemDetails(item.details, lang)}</div>
      <div class="item-rec">${translateItemRec(item.recommendation, lang)}</div>
    </div>
    <div>
      <div style="font-size:0.8rem;color:var(--text-dim);text-align:right">${item.score}/${item.maxScore}</div>
      <div class="score-bar"><div class="score-fill" style="width:${item.score}%;background:linear-gradient(90deg,${gradientFrom},${gradientTo})"></div></div>
    </div>
  </div>\n`;
  }

  return html;
}

function renderPriorityFixes(audit: AuditResult, lang: string): string {
  const actions = calculatePriorityActions(audit);
  if (actions.length === 0) return '';

  const title = lang === 'lt' ? 'Prioritetiniai pataisymai' : 'Priority Fixes';
  const subtitle = lang === 'lt'
    ? 'Didžiausio poveikio veiksmai jūsų balui pagerinti, surikiuoti pagal taškų poveikį.'
    : 'Highest-impact actions to improve your score, ranked by point impact.';

  return `
  <div class="priority-fixes">
    <h2>${title}</h2>
    <p style="color:var(--text-dim);font-size:0.9rem;margin-bottom:1rem">${subtitle}</p>
${actions.map(action => `    <div class="priority-fix-card">
      <div class="priority-impact">
        <div class="priority-impact-value">+${action.scoreImpact}</div>
        <div class="priority-impact-label">${lang === 'lt' ? 'taškai' : 'points'}</div>
      </div>
      <div class="priority-fix-body">
        <div class="priority-fix-title">
          ${translateItemName(action.name, lang)}
          <span class="effort-pill effort-${action.effort}">${action.effort}</span>
        </div>
        <div class="priority-fix-rec">${getClientGuide(action.name, lang) || translateItemRec(action.recommendation, lang)}</div>
      </div>
    </div>`).join('\n')}
  </div>`;
}

/** Items that are auto-generated and don't need client action */
const AUTO_GENERATED_ITEMS = new Set([
  'robots.txt',
  'AI Bot Blocking',
  'sitemap.xml',
  'llms.txt',
  'llms-full.txt',
  'AI Policy (ai.txt / ai.json)',
  'security.txt',
  'tdmrep.json',
  'humans.txt',
  'manifest.json',
  'Structured Data (JSON-LD)',
]);

/** Weight order for sorting: critical first, then high, medium, low */
const CATEGORY_ORDER: Record<string, number> = { critical: 0, high: 1, seo: 2, eeat: 3, aeo: 4, medium: 5, low: 6 };

function getClientActionItems(audit: AuditResult): AuditItem[] {
  return audit.items
    .filter(item =>
      !AUTO_GENERATED_ITEMS.has(item.name) &&
      item.status !== 'pass' &&
      item.score < 100
    )
    .sort((a, b) => (CATEGORY_ORDER[a.category] ?? 9) - (CATEGORY_ORDER[b.category] ?? 9));
}

function getGradeColor(grade: string): string {
  if (grade.startsWith('A')) return '#34d399';
  if (grade === 'B') return '#60a5fa';
  if (grade === 'C') return '#fbbf24';
  if (grade === 'D') return '#fb923c';
  return '#f87171';
}

export function generateSummaryJson(
  audit: AuditResult,
  crawlResult: SiteCrawlResult,
): string {
  const summary = {
    site: {
      url: crawlResult.baseUrl,
      domain: crawlResult.domain,
      name: crawlResult.siteIdentity.name,
      pagesCrawled: crawlResult.crawlStats.totalPages,
      crawlTimeMs: crawlResult.crawlStats.totalTime,
    },
    audit: {
      overallScore: audit.overallScore,
      grade: audit.grade,
      summary: audit.summary,
      items: audit.items.map(i => ({
        name: i.name,
        category: i.category,
        score: i.score,
        status: i.status,
        details: i.details,
        recommendation: i.recommendation,
        ...(i.affectedUrls && i.affectedUrls.length > 0 ? { affectedUrls: i.affectedUrls } : {}),
      })),
    },
    generated: new Date().toISOString(),
  };

  return JSON.stringify(summary, null, 2) + '\n';
}
