/**
 * PDF Report Generator — renders HTML audit/comparison reports to professional PDFs.
 *
 * Uses Playwright (already in devDependencies) to render the existing HTML reports
 * to PDF with print-optimized styling and gauge chart visualizations.
 */

/**
 * Generate a PDF from HTML content using Playwright.
 * Throws an informative error if Playwright is not installed.
 */
export async function generatePdfFromHtml(
  htmlContent: string,
  outputPath: string,
  options?: {
    format?: 'A4' | 'Letter';
    landscape?: boolean;
  },
): Promise<void> {
  let chromium;
  try {
    const pw = await import('playwright');
    chromium = pw.chromium;
  } catch {
    throw new Error(
      'PDF generation requires Playwright.\n' +
      'Install it with: npx playwright install chromium'
    );
  }

  const browser = await chromium.launch({ headless: true });

  try {
    const page = await browser.newPage();

    // Set the HTML content
    await page.setContent(htmlContent, { waitUntil: 'networkidle' });

    // Inject print-specific CSS overrides
    await page.addStyleTag({
      content: `
        @media print {
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .category-header {
            page-break-before: auto;
          }
          .category-section {
            page-break-inside: avoid;
          }
          .audit-item {
            page-break-inside: avoid;
          }
          /* Ensure score bars and colors print */
          .score-bar, .grade-circle, .stat-card {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          /* Ensure backgrounds print */
          * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
        }
      `,
    });

    // Inject score gauge SVG visualization
    await page.evaluate(() => {
      // Find the grade circle element and enhance it with an SVG gauge
      const gradeCircle = document.querySelector('.grade-circle');
      if (gradeCircle) {
        const scoreText = gradeCircle.textContent?.trim() || '';
        const scoreMatch = scoreText.match(/(\d+)/);
        const score = scoreMatch ? parseInt(scoreMatch[1], 10) : 0;

        // Determine color based on score
        let color = '#ef4444'; // red
        if (score >= 90) color = '#22c55e';       // green
        else if (score >= 70) color = '#3b82f6';   // blue
        else if (score >= 50) color = '#f59e0b';   // amber
        else if (score >= 30) color = '#f97316';   // orange

        const radius = 45;
        const circumference = 2 * Math.PI * radius;
        const dashOffset = circumference * (1 - score / 100);

        const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        svg.setAttribute('width', '120');
        svg.setAttribute('height', '120');
        svg.setAttribute('viewBox', '0 0 120 120');
        svg.style.display = 'block';
        svg.style.margin = '0 auto 8px';

        svg.innerHTML = `
          <circle cx="60" cy="60" r="${radius}" fill="none" stroke="#e5e7eb" stroke-width="8"/>
          <circle cx="60" cy="60" r="${radius}" fill="none" stroke="${color}" stroke-width="8"
                  stroke-dasharray="${circumference}" stroke-dashoffset="${dashOffset}"
                  stroke-linecap="round" transform="rotate(-90 60 60)"/>
          <text x="60" y="55" text-anchor="middle" font-size="28" font-weight="bold" fill="${color}">${score}</text>
          <text x="60" y="75" text-anchor="middle" font-size="12" fill="#6b7280">/ 100</text>
        `;

        gradeCircle.innerHTML = '';
        gradeCircle.appendChild(svg);
      }
    });

    // Generate PDF
    await page.pdf({
      path: outputPath,
      format: options?.format ?? 'A4',
      landscape: options?.landscape ?? false,
      printBackground: true,
      margin: {
        top: '1.5cm',
        bottom: '1.5cm',
        left: '1.5cm',
        right: '1.5cm',
      },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="width: 100%; font-size: 8px; color: #999; text-align: center; padding: 0 20px;">
          <span>GEO Compliance Report — Generated by geo-scraper</span>
          <span style="float: right;">Page <span class="pageNumber"></span> / <span class="totalPages"></span></span>
        </div>
      `,
    });
  } finally {
    await browser.close();
  }
}
