/**
 * Generate security.txt following RFC 9116.
 * Location: /.well-known/security.txt
 */

import type { SiteCrawlResult, GeneratorOptions } from '../crawler/page-data.js';

export function generateSecurityTxt(
  crawlResult: SiteCrawlResult,
  options: GeneratorOptions,
): string {
  const { siteIdentity, baseUrl, domain } = crawlResult;
  const hasRealEmail = !!(options.contactEmail || siteIdentity.contactEmail);
  const contactEmail = options.contactEmail || siteIdentity.contactEmail || `security@${domain}`;

  // Expiry: 1 year from generation
  const expiry = new Date();
  expiry.setFullYear(expiry.getFullYear() + 1);

  const lines: string[] = [];

  lines.push('# Security Policy');
  lines.push(`# ${siteIdentity.name || domain}`);
  lines.push('#');
  lines.push('# This file follows RFC 9116 (https://www.rfc-editor.org/rfc/rfc9116)');
  lines.push('# Generated by geo-scraper');
  if (!hasRealEmail) {
    lines.push('#');
    lines.push('# TODO: Replace the placeholder email below with your actual security contact');
  }
  lines.push('');
  lines.push(`Contact: mailto:${contactEmail}`);
  lines.push(`Expires: ${expiry.toISOString()}`);
  lines.push(`Preferred-Languages: en`);
  lines.push(`Canonical: ${baseUrl}/.well-known/security.txt`);
  lines.push('');

  return lines.join('\n');
}
